- name: Install and set up devops tools
  hosts: localhost
  become: true
  tasks:
  - name: Update the apt repo
    command: apt-get update
  - name: Install multiple packages
    package: name={{item}} state=present
    loop:
     - git
     - docker.io
     - openjdk-17-jdk
  - name: update apt-repo
    command: sudo apt-get update
  - name: install jenkins
    command: sudo apt-get install jenkins -y
  - name: start Jenkins and docker service
    service: name={{item}} state=started
    loop:
    - jenkins
    - docker
  - name: Add user to the Docker group
    ansible.builtin.user:
     name: "jenkins"
     groups: docker
     append: yes
  - name: Restart Jenkins
    ansible.builtin.service:
     name: jenkins
     state: restarted
